-- 코드를 입력하세요
SELECT G.TITLE, G.BOARD_ID,R.REPLY_ID,R.WRITER_ID,R.CONTENTS,DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d')
FROM USED_GOODS_BOARD AS G
JOIN USED_GOODS_REPLY AS R
ON G.BOARD_ID = R.BOARD_ID
WHERE YEAR(G.CREATED_DATE) = 2022 AND MONTH(G.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE ASC, G.TITLE ASC